# Generated by Django 2.1.3 on 2019-06-08 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='studentrg',
            name='RegNo',
        ),
        migrations.AddField(
            model_name='comms',
            name='subject',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myFile.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replys',
            name='Content',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrg',
            name='interests',
            field=models.ManyToManyField(related_name='interested_student', to='myFile.Subject'),
        ),
        migrations.AlterField(
            model_name='replys',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='replys',
            name='msg',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myFile.Message'),
            preserve_default=False,
        ),
    ]
