# Generated by Django 2.1.3 on 2019-06-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
        ),
        migrations.AlterField(
            model_name='ylinks',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
