# Generated by Django 2.1.3 on 2019-06-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0002_auto_20190610_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course', unique=True),
        ),
    ]
