# Generated by Django 2.1.3 on 2019-06-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0004_auto_20190611_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Period'),
        ),
    ]
