# Generated by Django 2.1.3 on 2019-06-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0005_auto_20190611_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='Cf',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Title',
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
            preserve_default=False,
        ),
    ]
