# Generated by Django 2.1.3 on 2019-06-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0006_auto_20190611_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Period'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
