# Generated by Django 2.1.3 on 2019-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0007_auto_20190611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_students', to='myFile.Course'),
        ),
    ]
