# Generated by Django 2.1.3 on 2019-06-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0008_auto_20190611_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrg',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Studentrg',
        ),
    ]
