# Generated by Django 2.1.3 on 2019-06-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0009_auto_20190612_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comms',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='myFile.Course'),
        ),
    ]
