# Generated by Django 2.1.3 on 2019-06-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0010_auto_20190612_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Period',
        ),
        migrations.RemoveField(
            model_name='ylinks',
            name='Period',
        ),
    ]
