# Generated by Django 2.1.3 on 2019-06-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0011_auto_20190613_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comms',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFile.Unit'),
        ),
    ]
