# Generated by Django 2.1.3 on 2019-06-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0013_auto_20190621_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myFile.Course'),
        ),
    ]
