# Generated by Django 2.1.3 on 2019-06-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFile', '0015_auto_20190625_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',)},
        ),
    ]
